### ISSUE TITLE
Issue under Windows 7: Description of the Launchpad S is "USB-Audiodevice" instead of "Launchpad S"

### ISSUE THREAD

**Issue by pneugebala** [OlivierCroisier/LP4J#1]
Hi,

in your autodetect-functions in

"net.thecodersbreakfast.lp4j.midi.MidiDeviceConfiguration.java"
("autodetectOutputDevice()" and "autodetectInputDevice()")

you used

"info.getDescription().contains(DEVICE_SIGNATURE)", where DEVICE_SIGNATURE = "Launchpad S"

which somehow doesn´t work on my PC, because the description is "USB-Audiodevice" instead of "Launchpad S". By using something like

"(info.getDescription().contains(DEVICE_SIGNATURE)) || (info.getName().contains(DEVICE_SIGNATURE))"

it just works fine.

**Comment by themorfeus** [comment]
Same here, Win 10

**Comment by OlivierCroisier** [comment]
Thank you for using LP4J and reporting issues !
I committed the suggested improvement.
