### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by wouterdedroog** [OlivierCroisier/LP4J#4]
Where can I download a compiled jar, or do I need to compile it myself?

**Comment by OlivierCroisier** [comment]
Hi,
Sorry for the latency, I didn't see your issue.
You need to clone or download the project, then package the librairy with Maven : `mvn clean install` 
(or just `mvn clean package` if you plan to use the generated jar in a non-maven project).
Best regards, and thanks for trying LP4J !
